<?xml version="1.0"?>
<robot 
  xmlns:xacro="http://ros.org/wiki/xacro" name="mars">


  <xacro:property name="properties" value="${load_yaml('../config/properties.yaml')}"/>

  <!--xacro:property name="pi" value="3.1415"/-->
  <!-- Mobile platform properties -->
  <xacro:property name="mob_base_length" value="${properties['mobile_platform']['base_length']}"/>
  <xacro:property name="mob_base_width" value="${properties['mobile_platform']['base_width']}"/>
  <xacro:property name="mob_base_height" value="${properties['mobile_platform']['base_height']}"/>
  <xacro:property name="wheel_radius" value="${properties['mobile_platform']['wheel_radius']}"/>
  <xacro:property name="wheels_distance" value="${properties['mobile_platform']['wheels_distance']}"/>

  <!-- Prismatic joint properties -->
  <xacro:property name="mob_base_to_prism_vert_distance" value="${properties['prismatic_joint']['mob_base_to_prism_vert_distance']}"/>
  <xacro:property name="mob_base_to_prism_hor_distance" value="${properties['prismatic_joint']['mob_base_to_prism_hor_distance']}"/>
  <xacro:property name="prism_ur5_safety_distance" value="${properties['prismatic_joint']['prism_ur5_safety_distance']}"/>  
  <xacro:property name="prism_base_length" value="${properties['prismatic_joint']['base_length']}"/>
  <xacro:property name="prism_base_width" value="${properties['prismatic_joint']['base_width']}"/>
  <xacro:property name="prism_base_height" value="${properties['prismatic_joint']['base_height']}"/>
  <xacro:property name="prism_plate_length" value="${properties['prismatic_joint']['plate_length']}"/>
  <xacro:property name="prism_plate_width" value="${properties['prismatic_joint']['plate_width']}"/>
  <xacro:property name="prism_plate_height" value="${properties['prismatic_joint']['plate_height']}"/>  

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="lightgrey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </xacro:macro>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <!--origin rpy="0 0 0" xyz="0 0 ${mob_base_height/2}"/>
      <geometry>
        <box size="${mob_base_length} ${mob_base_width} ${mob_base_height}"/>
      </geometry>
      <material name="lightgrey"/-->
      <origin xyz="0 0 0.047965"/>
      <geometry>
         <mesh filename="package://mars_description/meshes/cubi-mobile_platform.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${mob_base_height/2}"/>
      <geometry>
        <box size="${mob_base_length} ${mob_base_width} ${mob_base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <mesh filename="package://mars_description/meshes/cubi-wheel.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="0.03"/>
        </geometry>
      </collision>
      <xacro:default_inertial mass="1"/>
    </link>
    <joint name="${prefix}_wheel" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${reflect*wheels_distance/2} 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheel prefix="right" reflect="-1"/>
  <xacro:wheel prefix="left" reflect="1"/>

  <!-- Prismatic joint base (toyo eth-14)-->
  <link name="prism_base">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${prism_base_height/2-mob_base_to_prism_vert_distance+mob_base_height}"/>
      <geometry>
          <mesh filename="package://mars_description/meshes/cubi-prism_base.dae"/>
      </geometry>
      
      <!--geometry>
        <box size="${prism_base_length} ${prism_base_width} ${prism_base_height}"/>
      </geometry>
      <material name="lightgrey"/-->
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${prism_base_height/2-mob_base_to_prism_vert_distance+mob_base_height}"/>
      <geometry>
        <box size="${prism_base_length} ${prism_base_width} ${prism_base_height}"/>
      </geometry>
    </collision>
  </link>
  <joint name="base_link_to_prism_base" type="fixed">
    <axis xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="prism_base"/>
    <origin xyz="${-1*prism_base_width/2-0.01-mob_base_to_prism_hor_distance} 0 ${mob_base_to_prism_vert_distance}" rpy="0 0 0"/>
  </joint>

  <!-- Prismatic joint -->
  <link name="prism_plate">
    <visual>
      <geometry>
        <mesh filename="package://mars_description/meshes/cubi-prism_plate.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="${-1*prism_plate_length/2} 0 0"/>
      <geometry>
        <box size="${prism_plate_length} ${prism_plate_width} ${prism_plate_height}"/>
      </geometry>
    </collision>
  </link>
  <joint name="prismatic_joint" type="prismatic">
    <parent link="prism_base"/>
    <child link="prism_plate"/>
    <axis xyz="0 0 1" rpy="0 0 0" />
    <limit effort="1000.0" lower="0.0" upper="0.4" velocity="0.1"/>
    <origin xyz="${prism_base_width/2+0.01} 0 ${prism_ur5_safety_distance}" rpy="0 0 0"/>
  </joint>

  <!-- ur5 -->
  <xacro:include filename="$(find mars_description)/urdf/ur5.urdf.xacro"/>
  <!-- arm -->
  <xacro:ur5_robot prefix="ur5_" joint_limited="true"/>

  <joint name="prism_to_ur5" type="fixed">
    <parent link="prism_plate" />
    <child link = "ur5_base_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 ${pi/2} 0.0" />
  </joint>
</robot>